/* eslint-disable camelcase */
module.exports = [
  {
    sides: ["1RD", "1RD", "+2RD", "1F", "1Sh", "-"],
    set_code: "CONV",
    set_name: "Convergence",
    type_code: "character",
    type_name: "Character",
    faction_code: "red",
    faction_name: "Command",
    affiliation_code: "hero",
    affiliation_name: "Hero",
    rarity_code: "R",
    rarity_name: "Rare",
    subtypes: [
      {
        code: "trooper",
        name: "Trooper",
      },
      {
        code: "guard",
        name: "Guard",
      },
    ],
    position: 74,
    code: "09074",
    ttscardid: "50003",
    name:   "Naboo Palace Guard",
    subtitle: null,
    cost: null,
    health: 9,
    points: "8",
    text:
      "While you have a <i>leader</i> in play, this character gains Guardian.",
    deck_limit: 3,
    flavor: null,
    illustrator: " ",
    is_unique: false,
    has_die: true,
    has_errata: false,
    url: "https://swdestinydb.com/card/09074",
    imagesrc: "https://swdestinydb.com/bundles/cards/en/09/09074.jpg",
    label: "Naboo Palace Guard",
    cp: 800,
  },
  {
    sides: [
    "1RD",
    "2RD",
    "2RD1",
    "1R",
    "-",
    "-"
    ],
    set_code: "AW",
    set_name: "Awakenings",
    type_code: "character",
    type_name: "Character",
    faction_code: "red",
    faction_name: "Command",
    affiliation_code: "villain",
    affiliation_name: "Villain",
    rarity_code: "R",
    rarity_name: "Rare",
    subtypes: [
    {
    code: "trooper",
    name: "Trooper"
    }
    ],
    position: 2,
    code: "01002",
    ttscardid: "1301",
    name: "First Order Stormtrooper",
    subtitle: null,
    cost: null,
    health: 7,
    points: "7",
    text: null,
    deck_limit: 4,
    flavor: "Members of this new generation of stormtroopers are trained from birth and fed a steady diet of First Order propaganda to ensure absolute loyalty.",
    illustrator: null,
    is_unique: false,
    has_die: true,
    has_errata: true,
    reprints: [
    "09020"
    ],
    url: "https://swdestinydb.com/card/01002",
    imagesrc: "https://swdestinydb.com/bundles/cards/en/01/01002.jpg",
    label: "First Order Stormtrooper",
    cp: 700
    },
    {
      sides: [
      "2MD",
      "2MD",
      "3MD1",
      "1Dr",
      "1R",
      "-"
      ],
      set_code: "AW",
      set_name: "Awakenings",
      type_code: "character",
      type_name: "Character",
      faction_code: "red",
      faction_name: "Command",
      affiliation_code: "villain",
      affiliation_name: "Villain",
      rarity_code: "R",
      rarity_name: "Rare",
      subtypes: [
      {
      code: "leader",
      name: "Leader"
      }
      ],
      position: 3,
      code: "01003",
      ttscardid: "1302",
      name: "General Grievous",
      subtitle: "Jedi Hunter",
      cost: null,
      health: 10,
      points: "13/18",
      text: "Before an opponent's character is defeated, you may move one of their non-<i>ability</i> upgrades to this character.",
      deck_limit: 1,
      flavor: null,
      illustrator: "Romana Kendelic",
      is_unique: true,
      has_die: true,
      has_errata: true,
      url: "https://swdestinydb.com/card/01003",
      imagesrc: "https://swdestinydb.com/bundles/cards/en/01/01003.jpg",
      label: "General Grievous - Jedi Hunter",
      cp: 1318
      },
];
