version: "2"
services:
    node_js:
        image: "jmgorduez/product-gallery-manager:${TAG}"
        ports:
        - "8080:8080"
        depends_on:
        - mongo
    mongo:
        image: mongo
        ports:
        - "27017:27017"