openapi: 3.0.1
info:
  title: Gaming cards
  description: Gaming cards API
  version: '0.1'
paths:
  /api/v1/show-gallery:
    get:
      description: Get all products
      responses:
        default:
          description: Response
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}