
name: Deploy to PROD

on: 
  milestone:
    types: [closed]
    branches: master

jobs:
  deploy:
    name: Upload to AWS PROD enviroment
    runs-on: ubuntu-latest
    needs: [deploy_to_PROD_checker]

    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    
    - name: Upload app images to the registry
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: jmgorduez/product-gallery-manager
        tag: ${{ github.sha }}
        registry: docker.io
        dockerfile: deploy-app-Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy app to AWS
      uses: appleboy/ssh-action@master
      env: 
        TAG: ${{ github.sha }}
      with:
        host: ${{ secrets.AWS_SERVER_QA }}
        username: ${{ secrets.AWS_USER_QA }}
        key: ${{ secrets.EC2 }}
        port: 22
        envs: TAG
        script: |
          sudo docker rmi -f $(sudo docker images 'mong' -q)
          sudo docker rmi -f $(sudo docker images 'jmgorduez/product-gallery-manager' -q)
          sudo docker run -d -p 27017:27017 mongo
          sudo docker run -d -p 8080:8080 "jmgorduez/product-gallery-manager:${TAG}"
      
    - name: Slack Notification
      uses: sonots/slack-notice-action@v3
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()