
name: Deploy to QA

on:
  push:
    branches: master

jobs:
  deploy_to_QA_checker:
    name: Deploy to QA checker
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Code checkout
      uses: actions/checkout@v2

    - name: Setup Node environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM ci
      run: |
        npm ci

    - name: NPM build  
      run: |
        npm run build --if-present

    - name: Code review  
      run: |
        npm run eslint-src
        npm run eslint-tests  

    - name: Running unit tests  
      run: |
        npm test    
      env:
        CI: true

  deploy:
    name: Upload to AWS QA enviroment
    runs-on: ubuntu-latest
    needs: [deploy_to_QA_checker]

    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    
    - name: Upload app images to the registry
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: jmgorduez/product-gallery-manager
        tag: ${GITHUB_SHA}
        registry: docker.io
        dockerfile: deploy-app-Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to AWS
      uses: appleboy/ssh-action@master
        env:
          USERNAME: ubutu
          HOST: ec2-18-224-213-35.us-east-2.compute.amazonaws.com
          SCRIPT: docker --version
          KEY: ${{ secrets.EC2 }}