name: Deploy to PRO

on:
  release:
    types: [published]
    branches: master 

jobs:
  deploy_to_PRO:
    name: Upload to AWS PRO enviroment 
    runs-on: ubuntu-latest

    steps:
    - name: Retag to latest
      uses: ybrin/retag-docker-image@0.1.0
      with:
        registry: docker.io
        name: jmgorduez/product-gallery-manager
        old_tag: "QA"
        new_tag: "PRO"
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy app to AWS
      uses: appleboy/ssh-action@master
      env: 
        TAG: "PRO"
      with:
        host: ec2-3-16-209-207.us-east-2.compute.amazonaws.com
        username: ${{ secrets.AWS_USER_PRO }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: 22
        envs: TAG
        script: | 
          sudo docker rm -f -v product-gallery-manager
          sudo docker rmi -f $(sudo docker images 'jmgorduez/product-gallery-manager' -q)
          sudo docker run -d -p 8080:8080 --network product-gallery-network --name product-gallery-manager "jmgorduez/product-gallery-manager:${TAG}"
      
    - name: Slack Notification
      uses: sonots/slack-notice-action@v3
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()