name: Deploy to PRO

on:
  release:
    types: [published]
    branches: master 

jobs:
  deploy_to_PRO:
    name: Upload to AWS PRO enviroment
    runs-on: ubuntu-latest

    steps:
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull image
      run: docker pull 'jmgorduez/product-gallery-manager:QA'

    - name: Tags image
      run: |
        docker tag 'jmgorduez/product-gallery-manager:QA' 'jmgorduez/product-gallery-manager:PRO'

    - name: Push image
      run: |
        docker push 'jmgorduez/product-gallery-manager:PRO'

    - name: Deploy app to AWS
      uses: appleboy/ssh-action@master
      env: 
        TAG: "PRO"
      with:
        host: ec2-3-16-209-207.us-east-2.compute.amazonaws.com
        username: ${{ secrets.AWS_USER_PRO }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: 22
        envs: TAG
        script: | 
          docker rm -f -v product-gallery-manager
          docker rmi -f $(sudo docker images 'jmgorduez/product-gallery-manager' -q)
          docker run -d -p 8080:8080 --network product-gallery-network --name product-gallery-manager "jmgorduez/product-gallery-manager:${TAG}"
      
    - name: Slack Notification
      uses: sonots/slack-notice-action@v3
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()