
name: Deploy to QA

on:
  push:
    branches: master

jobs:
  deploy_to_QA_checker:
    name: Deploy to QA checker
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Code checkout
      uses: actions/checkout@v2

    - name: Setup Node environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM ci
      run: |
        npm ci

    - name: NPM build  
      run: |
        npm run build --if-present

    - name: Code review  
      run: |
        npm run eslint-src
        npm run eslint-tests  

    - name: Running unit tests  
      run: |
        sudo apt-get install gnupg
        wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse"
        sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
        sudo apt-get update
        sudo apt-get install -y mongodb
        mongo -u USER -p PASSWORD localhost:27017 --authenticationDatabase test
        npm test    
      env:
        CI: true

  deploy:
    name: Upload to AWS QA enviroment
    runs-on: ubuntu-latest
    needs: [deploy_to_QA_checker]

    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    
    - name: Upload app images to the registry
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: jmgorduez/product-gallery-manager
        tag: ${{ github.sha }}
        registry: docker.io
        dockerfile: deploy-app-Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy app to AWS
      uses: appleboy/ssh-action@master
      env: 
        TAG: ${{ github.sha }}
      with:
        host: ${{ secrets.AWS_SERVER_QA }}
        username: ${{ secrets.AWS_USER_QA }}
        key: ${{ secrets.EC2 }}
        port: 22
        envs: TAG
        script: |
          sudo docker rm -f $(sudo docker ps -a -q)
          sudo docker rmi -f $(sudo docker images -q)
          sudo docker run -d -p 27017:27017 mongo
          sudo docker run -d -p 8080:8080 "jmgorduez/product-gallery-manager:${TAG}"
      
    - name: Slack Notification
      uses: sonots/slack-notice-action@v3
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()