
name: Deploy to QA

on:
  push:
    branches: master

jobs:
  deploy_to_QA_checker:
    name: Deploy to QA checker
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Code checkout
      uses: actions/checkout@v2

    - name: Setup Node environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM ci
      run: |
        npm ci

    - name: NPM build  
      run: |
        npm run build --if-present

    - name: Code review  
      run: |
        npm run eslint-src
        npm run eslint-tests  

    - name: Running unit tests  
      run: |
        npm test    
      env:
        CI: true

  deploy:
    name: Upload to AWS QA enviroment
    runs-on: ubuntu-latest
    needs: [deploy_to_QA_checker]

    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    
    - name: Upload app images to the registry
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: jmgorduez/gaming-cards
        tag: deploy-to-qa
        registry: docker.io
        dockerfile: deploy-Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Copy files to S3 with the AWS CLI
      run: |
        aws s3 sync . s3://my-s3-website-bucket 